run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - testdata
    - mocks
    - internal/mocks
    - pb

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - gofmt
    - goimports
    - gocritic
    - revive
    - unconvert
    - ineffassign
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
  govet:
    check-shadowing: true
  staticcheck:
    checks:
      - all
      - "-ST1000" # disable package naming checks
  revive:
    rules:
      - name: package-comments
        disabled: true