version: '3.5'

services:
  roomservice:
    depends_on:
      - postgres
    container_name: room_service
    build:
      context: ../
      dockerfile: ./internal/services/room_service/docker/Dockerfile
    ports:
        - "50051:50051"
        - "8081:8081"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: