syntax = "proto3";

package payment;

option go_package = "we_ride/internal/services/payment_service/pb";

service PaymentService {
  rpc GetBalance(GetBalanceRequest) returns (BalanceResponse);
  rpc Deposit(AmountRequest) returns (TransactionResponse);
  rpc Withdraw(AmountRequest) returns (TransactionResponse);
  rpc CreateTransfer(TransferRequest) returns (TransactionResponse);
}

message GetBalanceRequest {
  string user_id = 1;
}

message BalanceResponse {
  int64 amount = 1;
}

message AmountRequest {
  string user_id = 1;
  int64 amount = 2;
}

message TransferRequest {
  string from_user_id = 1;
  string to_user_id = 2;
  int64 amount = 3;
  string ride_id = 4;
}

message TransactionResponse {
  string transaction_id = 1;
  bool success = 2;
}