// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: room.proto

package roomservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статусы комнаты
type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNSPECIFIED RoomStatus = 0 // Статус не указан
	RoomStatus_ROOM_STATUS_WAITING     RoomStatus = 1 // Ожидание участников
	RoomStatus_ROOM_STATUS_FULL        RoomStatus = 2 // Комната заполнена
	RoomStatus_ROOM_STATUS_ON_RIDE     RoomStatus = 3 // Поездка в процессе
	RoomStatus_ROOM_STATUS_COMPLETED   RoomStatus = 4 // Поездка завершена
	RoomStatus_ROOM_STATUS_CANCELLED   RoomStatus = 5 // Поездка отменена
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_UNSPECIFIED",
		1: "ROOM_STATUS_WAITING",
		2: "ROOM_STATUS_FULL",
		3: "ROOM_STATUS_ON_RIDE",
		4: "ROOM_STATUS_COMPLETED",
		5: "ROOM_STATUS_CANCELLED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_UNSPECIFIED": 0,
		"ROOM_STATUS_WAITING":     1,
		"ROOM_STATUS_FULL":        2,
		"ROOM_STATUS_ON_RIDE":     3,
		"ROOM_STATUS_COMPLETED":   4,
		"ROOM_STATUS_CANCELLED":   5,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // Широта
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // Долгота
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`       // Адрес в текстовом формате
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                // Модель машины
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`                                // Цвет машины
	PlateNumber   string                 `protobuf:"bytes,3,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"` // Номер машины
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Vehicle) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

type Room struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                           // Уникальный идентификатор комнаты
	CreatorId      string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`                  // ID создателя комнаты
	Members        []string               `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`                                       // ID участников
	StartLocation  *Location              `protobuf:"bytes,4,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`      // Место посадки
	EndLocation    *Location              `protobuf:"bytes,5,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`            // Место назначения
	AvailableSeats int32                  `protobuf:"varint,6,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`  // Максимальное количество участников
	Status         RoomStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=service.room.v1.RoomStatus" json:"status,omitempty"`        // Текущий статус комнаты
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // Время создания
	ScheduledTime  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`      // Запланированное время поездки
	TotalPrice     float32                `protobuf:"fixed32,10,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`            // Общая стоимость поездки
	CostPerMember  float32                `protobuf:"fixed32,11,opt,name=cost_per_member,json=costPerMember,proto3" json:"cost_per_member,omitempty"` // Стоимость на одного участника
	Vehicle        *Vehicle               `protobuf:"bytes,12,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Room) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Room) GetStartLocation() *Location {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

func (x *Room) GetEndLocation() *Location {
	if x != nil {
		return x.EndLocation
	}
	return nil
}

func (x *Room) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *Room) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *Room) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Room) GetCostPerMember() float32 {
	if x != nil {
		return x.CostPerMember
	}
	return 0
}

func (x *Room) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // ID пользователя
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // Имя
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // Ссылка на аватар
	Rating        float32                `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`                      // Рейтинг пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`             // ID создателя
	StartLocation *Location              `protobuf:"bytes,2,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"` // Место посадки
	EndLocation   *Location              `protobuf:"bytes,3,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`       // Место назначения
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"` // Запланированное время
	MaxMembers    int32                  `protobuf:"varint,5,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`         // Максимальное количество участников
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateRoomRequest) GetStartLocation() *Location {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

func (x *CreateRoomRequest) GetEndLocation() *Location {
	if x != nil {
		return x.EndLocation
	}
	return nil
}

func (x *CreateRoomRequest) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *CreateRoomRequest) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"` // Созданная комната
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // ID комнаты
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"` // Обновленная информация о комнате
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type ExitRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // ID комнаты
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitRoomRequest) Reset() {
	*x = ExitRoomRequest{}
	mi := &file_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomRequest) ProtoMessage() {}

func (x *ExitRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomRequest.ProtoReflect.Descriptor instead.
func (*ExitRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *ExitRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ExitRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExitRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Флаг успешного выхода
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitRoomResponse) Reset() {
	*x = ExitRoomResponse{}
	mi := &file_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomResponse) ProtoMessage() {}

func (x *ExitRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomResponse.ProtoReflect.Descriptor instead.
func (*ExitRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *ExitRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FindRoomRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PickupLocation  *Location              `protobuf:"bytes,1,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`    // Желаемое место посадки
	DropoffLocation *Location              `protobuf:"bytes,2,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"` // Желаемое место назначения
	TimeRangeStart  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_range_start,json=timeRangeStart,proto3" json:"time_range_start,omitempty"`  // Начало временного диапазона
	TimeRangeEnd    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time_range_end,json=timeRangeEnd,proto3" json:"time_range_end,omitempty"`        // Конец временного диапазона
	RequiredSeats   int32                  `protobuf:"varint,5,opt,name=required_seats,json=requiredSeats,proto3" json:"required_seats,omitempty"`      // Требуемое количество мест
	MaxDistance     float32                `protobuf:"fixed32,6,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`           // Максимальное расстояние (в метрах)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindRoomRequest) Reset() {
	*x = FindRoomRequest{}
	mi := &file_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoomRequest) ProtoMessage() {}

func (x *FindRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoomRequest.ProtoReflect.Descriptor instead.
func (*FindRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *FindRoomRequest) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *FindRoomRequest) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *FindRoomRequest) GetTimeRangeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeRangeStart
	}
	return nil
}

func (x *FindRoomRequest) GetTimeRangeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeRangeEnd
	}
	return nil
}

func (x *FindRoomRequest) GetRequiredSeats() int32 {
	if x != nil {
		return x.RequiredSeats
	}
	return 0
}

func (x *FindRoomRequest) GetMaxDistance() float32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

type FindRoomResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableRooms []*Room                `protobuf:"bytes,1,rep,name=available_rooms,json=availableRooms,proto3" json:"available_rooms,omitempty"` // Найденные доступные комнаты
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindRoomResponse) Reset() {
	*x = FindRoomResponse{}
	mi := &file_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoomResponse) ProtoMessage() {}

func (x *FindRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoomResponse.ProtoReflect.Descriptor instead.
func (*FindRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *FindRoomResponse) GetAvailableRooms() []*Room {
	if x != nil {
		return x.AvailableRooms
	}
	return nil
}

type GetRoomDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // ID комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomDetailsRequest) Reset() {
	*x = GetRoomDetailsRequest{}
	mi := &file_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailsRequest) ProtoMessage() {}

func (x *GetRoomDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomDetailsRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomDetailsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`       // Информация о комнате
	Members       []*UserInfo            `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"` // Информация об участниках
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomDetailsResponse) Reset() {
	*x = GetRoomDetailsResponse{}
	mi := &file_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailsResponse) ProtoMessage() {}

func (x *GetRoomDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomDetailsResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoomDetailsResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomDetailsResponse) GetMembers() []*UserInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type StreamRoomUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // ID комнаты
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя (для аутентификации)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRoomUpdatesRequest) Reset() {
	*x = StreamRoomUpdatesRequest{}
	mi := &file_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRoomUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRoomUpdatesRequest) ProtoMessage() {}

func (x *StreamRoomUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRoomUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamRoomUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{14}
}

func (x *StreamRoomUpdatesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StreamRoomUpdatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RoomUpdate_MemberJoined
	//	*RoomUpdate_MemberLeft
	//	*RoomUpdate_StatusChanged
	//	*RoomUpdate_LocationUpdated
	//	*RoomUpdate_PaymentUpdated
	Update        isRoomUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomUpdate) Reset() {
	*x = RoomUpdate{}
	mi := &file_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUpdate) ProtoMessage() {}

func (x *RoomUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUpdate.ProtoReflect.Descriptor instead.
func (*RoomUpdate) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{15}
}

func (x *RoomUpdate) GetUpdate() isRoomUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RoomUpdate) GetMemberJoined() *MemberJoined {
	if x != nil {
		if x, ok := x.Update.(*RoomUpdate_MemberJoined); ok {
			return x.MemberJoined
		}
	}
	return nil
}

func (x *RoomUpdate) GetMemberLeft() *MemberLeft {
	if x != nil {
		if x, ok := x.Update.(*RoomUpdate_MemberLeft); ok {
			return x.MemberLeft
		}
	}
	return nil
}

func (x *RoomUpdate) GetStatusChanged() *RoomStatusChanged {
	if x != nil {
		if x, ok := x.Update.(*RoomUpdate_StatusChanged); ok {
			return x.StatusChanged
		}
	}
	return nil
}

func (x *RoomUpdate) GetLocationUpdated() *LocationUpdated {
	if x != nil {
		if x, ok := x.Update.(*RoomUpdate_LocationUpdated); ok {
			return x.LocationUpdated
		}
	}
	return nil
}

func (x *RoomUpdate) GetPaymentUpdated() *PaymentUpdated {
	if x != nil {
		if x, ok := x.Update.(*RoomUpdate_PaymentUpdated); ok {
			return x.PaymentUpdated
		}
	}
	return nil
}

type isRoomUpdate_Update interface {
	isRoomUpdate_Update()
}

type RoomUpdate_MemberJoined struct {
	MemberJoined *MemberJoined `protobuf:"bytes,1,opt,name=member_joined,json=memberJoined,proto3,oneof"` // Новый участник присоединился
}

type RoomUpdate_MemberLeft struct {
	MemberLeft *MemberLeft `protobuf:"bytes,2,opt,name=member_left,json=memberLeft,proto3,oneof"` // Участник покинул комнату
}

type RoomUpdate_StatusChanged struct {
	StatusChanged *RoomStatusChanged `protobuf:"bytes,3,opt,name=status_changed,json=statusChanged,proto3,oneof"` // Изменился статус комнаты
}

type RoomUpdate_LocationUpdated struct {
	LocationUpdated *LocationUpdated `protobuf:"bytes,4,opt,name=location_updated,json=locationUpdated,proto3,oneof"` // Изменилось место посадки/назначения
}

type RoomUpdate_PaymentUpdated struct {
	PaymentUpdated *PaymentUpdated `protobuf:"bytes,5,opt,name=payment_updated,json=paymentUpdated,proto3,oneof"` // Изменились условия оплаты
}

func (*RoomUpdate_MemberJoined) isRoomUpdate_Update() {}

func (*RoomUpdate_MemberLeft) isRoomUpdate_Update() {}

func (*RoomUpdate_StatusChanged) isRoomUpdate_Update() {}

func (*RoomUpdate_LocationUpdated) isRoomUpdate_Update() {}

func (*RoomUpdate_PaymentUpdated) isRoomUpdate_Update() {}

type MemberJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // Информация о новом участнике
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberJoined) Reset() {
	*x = MemberJoined{}
	mi := &file_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberJoined) ProtoMessage() {}

func (x *MemberJoined) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberJoined.ProtoReflect.Descriptor instead.
func (*MemberJoined) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{16}
}

func (x *MemberJoined) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type MemberLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя, который покинул комнату
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLeft) Reset() {
	*x = MemberLeft{}
	mi := &file_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLeft) ProtoMessage() {}

func (x *MemberLeft) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLeft.ProtoReflect.Descriptor instead.
func (*MemberLeft) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{17}
}

func (x *MemberLeft) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     RoomStatus             `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=service.room.v1.RoomStatus" json:"new_status,omitempty"` // Новый статус комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStatusChanged) Reset() {
	*x = RoomStatusChanged{}
	mi := &file_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatusChanged) ProtoMessage() {}

func (x *RoomStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatusChanged.ProtoReflect.Descriptor instead.
func (*RoomStatusChanged) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{18}
}

func (x *RoomStatusChanged) GetNewStatus() RoomStatus {
	if x != nil {
		return x.NewStatus
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

type LocationUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewLocation   *Location              `protobuf:"bytes,1,opt,name=new_location,json=newLocation,proto3" json:"new_location,omitempty"` // Новое местоположение
	IsPickup      bool                   `protobuf:"varint,2,opt,name=is_pickup,json=isPickup,proto3" json:"is_pickup,omitempty"`         // true - место посадки, false - место назначения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdated) Reset() {
	*x = LocationUpdated{}
	mi := &file_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdated) ProtoMessage() {}

func (x *LocationUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdated.ProtoReflect.Descriptor instead.
func (*LocationUpdated) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{19}
}

func (x *LocationUpdated) GetNewLocation() *Location {
	if x != nil {
		return x.NewLocation
	}
	return nil
}

func (x *LocationUpdated) GetIsPickup() bool {
	if x != nil {
		return x.IsPickup
	}
	return false
}

type PaymentUpdated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NewCostPerMember float32                `protobuf:"fixed32,2,opt,name=new_cost_per_member,json=newCostPerMember,proto3" json:"new_cost_per_member,omitempty"` // Новая стоимость на участника
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentUpdated) Reset() {
	*x = PaymentUpdated{}
	mi := &file_room_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentUpdated) ProtoMessage() {}

func (x *PaymentUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentUpdated.ProtoReflect.Descriptor instead.
func (*PaymentUpdated) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{20}
}

func (x *PaymentUpdated) GetNewCostPerMember() float32 {
	if x != nil {
		return x.NewCostPerMember
	}
	return 0
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\x0fservice.room.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"X\n" +
	"\aVehicle\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12!\n" +
	"\fplate_number\x18\x03 \x01(\tR\vplateNumber\"\xb1\x04\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembers\x12@\n" +
	"\x0estart_location\x18\x04 \x01(\v2\x19.service.room.v1.LocationR\rstartLocation\x12<\n" +
	"\fend_location\x18\x05 \x01(\v2\x19.service.room.v1.LocationR\vendLocation\x12'\n" +
	"\x0favailable_seats\x18\x06 \x01(\x05R\x0eavailableSeats\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.service.room.v1.RoomStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\x0escheduled_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12\x1f\n" +
	"\vtotal_price\x18\n" +
	" \x01(\x02R\n" +
	"totalPrice\x12&\n" +
	"\x0fcost_per_member\x18\v \x01(\x02R\rcostPerMember\x122\n" +
	"\avehicle\x18\f \x01(\v2\x18.service.room.v1.VehicleR\avehicle\"n\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x02R\x06rating\"\x96\x02\n" +
	"\x11CreateRoomRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12@\n" +
	"\x0estart_location\x18\x02 \x01(\v2\x19.service.room.v1.LocationR\rstartLocation\x12<\n" +
	"\fend_location\x18\x03 \x01(\v2\x19.service.room.v1.LocationR\vendLocation\x12A\n" +
	"\x0escheduled_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12\x1f\n" +
	"\vmax_members\x18\x05 \x01(\x05R\n" +
	"maxMembers\"?\n" +
	"\x12CreateRoomResponse\x12)\n" +
	"\x04room\x18\x01 \x01(\v2\x15.service.room.v1.RoomR\x04room\"C\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"=\n" +
	"\x10JoinRoomResponse\x12)\n" +
	"\x04room\x18\x01 \x01(\v2\x15.service.room.v1.RoomR\x04room\"C\n" +
	"\x0fExitRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\x10ExitRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xed\x02\n" +
	"\x0fFindRoomRequest\x12B\n" +
	"\x0fpickup_location\x18\x01 \x01(\v2\x19.service.room.v1.LocationR\x0epickupLocation\x12D\n" +
	"\x10dropoff_location\x18\x02 \x01(\v2\x19.service.room.v1.LocationR\x0fdropoffLocation\x12D\n" +
	"\x10time_range_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimeRangeStart\x12@\n" +
	"\x0etime_range_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ftimeRangeEnd\x12%\n" +
	"\x0erequired_seats\x18\x05 \x01(\x05R\rrequiredSeats\x12!\n" +
	"\fmax_distance\x18\x06 \x01(\x02R\vmaxDistance\"R\n" +
	"\x10FindRoomResponse\x12>\n" +
	"\x0favailable_rooms\x18\x01 \x03(\v2\x15.service.room.v1.RoomR\x0eavailableRooms\"0\n" +
	"\x15GetRoomDetailsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"x\n" +
	"\x16GetRoomDetailsResponse\x12)\n" +
	"\x04room\x18\x01 \x01(\v2\x15.service.room.v1.RoomR\x04room\x123\n" +
	"\amembers\x18\x02 \x03(\v2\x19.service.room.v1.UserInfoR\amembers\"L\n" +
	"\x18StreamRoomUpdatesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x84\x03\n" +
	"\n" +
	"RoomUpdate\x12D\n" +
	"\rmember_joined\x18\x01 \x01(\v2\x1d.service.room.v1.MemberJoinedH\x00R\fmemberJoined\x12>\n" +
	"\vmember_left\x18\x02 \x01(\v2\x1b.service.room.v1.MemberLeftH\x00R\n" +
	"memberLeft\x12K\n" +
	"\x0estatus_changed\x18\x03 \x01(\v2\".service.room.v1.RoomStatusChangedH\x00R\rstatusChanged\x12M\n" +
	"\x10location_updated\x18\x04 \x01(\v2 .service.room.v1.LocationUpdatedH\x00R\x0flocationUpdated\x12J\n" +
	"\x0fpayment_updated\x18\x05 \x01(\v2\x1f.service.room.v1.PaymentUpdatedH\x00R\x0epaymentUpdatedB\b\n" +
	"\x06update\"=\n" +
	"\fMemberJoined\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.service.room.v1.UserInfoR\x04user\"%\n" +
	"\n" +
	"MemberLeft\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x11RoomStatusChanged\x12:\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x1b.service.room.v1.RoomStatusR\tnewStatus\"l\n" +
	"\x0fLocationUpdated\x12<\n" +
	"\fnew_location\x18\x01 \x01(\v2\x19.service.room.v1.LocationR\vnewLocation\x12\x1b\n" +
	"\tis_pickup\x18\x02 \x01(\bR\bisPickup\"?\n" +
	"\x0ePaymentUpdated\x12-\n" +
	"\x13new_cost_per_member\x18\x02 \x01(\x02R\x10newCostPerMember*\xa7\x01\n" +
	"\n" +
	"RoomStatus\x12\x1b\n" +
	"\x17ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ROOM_STATUS_WAITING\x10\x01\x12\x14\n" +
	"\x10ROOM_STATUS_FULL\x10\x02\x12\x17\n" +
	"\x13ROOM_STATUS_ON_RIDE\x10\x03\x12\x19\n" +
	"\x15ROOM_STATUS_COMPLETED\x10\x04\x12\x19\n" +
	"\x15ROOM_STATUS_CANCELLED\x10\x052\x99\x04\n" +
	"\vRoomService\x12U\n" +
	"\n" +
	"CreateRoom\x12\".service.room.v1.CreateRoomRequest\x1a#.service.room.v1.CreateRoomResponse\x12O\n" +
	"\bJoinRoom\x12 .service.room.v1.JoinRoomRequest\x1a!.service.room.v1.JoinRoomResponse\x12O\n" +
	"\bExitRoom\x12 .service.room.v1.ExitRoomRequest\x1a!.service.room.v1.ExitRoomResponse\x12O\n" +
	"\bFindRoom\x12 .service.room.v1.FindRoomRequest\x1a!.service.room.v1.FindRoomResponse\x12a\n" +
	"\x0eGetRoomDetails\x12&.service.room.v1.GetRoomDetailsRequest\x1a'.service.room.v1.GetRoomDetailsResponse\x12]\n" +
	"\x11StreamRoomUpdates\x12).service.room.v1.StreamRoomUpdatesRequest\x1a\x1b.service.room.v1.RoomUpdate0\x01B\x0eZ\f/roomserviceb\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_room_proto_goTypes = []any{
	(RoomStatus)(0),                  // 0: service.room.v1.RoomStatus
	(*Location)(nil),                 // 1: service.room.v1.Location
	(*Vehicle)(nil),                  // 2: service.room.v1.Vehicle
	(*Room)(nil),                     // 3: service.room.v1.Room
	(*UserInfo)(nil),                 // 4: service.room.v1.UserInfo
	(*CreateRoomRequest)(nil),        // 5: service.room.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),       // 6: service.room.v1.CreateRoomResponse
	(*JoinRoomRequest)(nil),          // 7: service.room.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),         // 8: service.room.v1.JoinRoomResponse
	(*ExitRoomRequest)(nil),          // 9: service.room.v1.ExitRoomRequest
	(*ExitRoomResponse)(nil),         // 10: service.room.v1.ExitRoomResponse
	(*FindRoomRequest)(nil),          // 11: service.room.v1.FindRoomRequest
	(*FindRoomResponse)(nil),         // 12: service.room.v1.FindRoomResponse
	(*GetRoomDetailsRequest)(nil),    // 13: service.room.v1.GetRoomDetailsRequest
	(*GetRoomDetailsResponse)(nil),   // 14: service.room.v1.GetRoomDetailsResponse
	(*StreamRoomUpdatesRequest)(nil), // 15: service.room.v1.StreamRoomUpdatesRequest
	(*RoomUpdate)(nil),               // 16: service.room.v1.RoomUpdate
	(*MemberJoined)(nil),             // 17: service.room.v1.MemberJoined
	(*MemberLeft)(nil),               // 18: service.room.v1.MemberLeft
	(*RoomStatusChanged)(nil),        // 19: service.room.v1.RoomStatusChanged
	(*LocationUpdated)(nil),          // 20: service.room.v1.LocationUpdated
	(*PaymentUpdated)(nil),           // 21: service.room.v1.PaymentUpdated
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
}
var file_room_proto_depIdxs = []int32{
	1,  // 0: service.room.v1.Room.start_location:type_name -> service.room.v1.Location
	1,  // 1: service.room.v1.Room.end_location:type_name -> service.room.v1.Location
	0,  // 2: service.room.v1.Room.status:type_name -> service.room.v1.RoomStatus
	22, // 3: service.room.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	22, // 4: service.room.v1.Room.scheduled_time:type_name -> google.protobuf.Timestamp
	2,  // 5: service.room.v1.Room.vehicle:type_name -> service.room.v1.Vehicle
	1,  // 6: service.room.v1.CreateRoomRequest.start_location:type_name -> service.room.v1.Location
	1,  // 7: service.room.v1.CreateRoomRequest.end_location:type_name -> service.room.v1.Location
	22, // 8: service.room.v1.CreateRoomRequest.scheduled_time:type_name -> google.protobuf.Timestamp
	3,  // 9: service.room.v1.CreateRoomResponse.room:type_name -> service.room.v1.Room
	3,  // 10: service.room.v1.JoinRoomResponse.room:type_name -> service.room.v1.Room
	1,  // 11: service.room.v1.FindRoomRequest.pickup_location:type_name -> service.room.v1.Location
	1,  // 12: service.room.v1.FindRoomRequest.dropoff_location:type_name -> service.room.v1.Location
	22, // 13: service.room.v1.FindRoomRequest.time_range_start:type_name -> google.protobuf.Timestamp
	22, // 14: service.room.v1.FindRoomRequest.time_range_end:type_name -> google.protobuf.Timestamp
	3,  // 15: service.room.v1.FindRoomResponse.available_rooms:type_name -> service.room.v1.Room
	3,  // 16: service.room.v1.GetRoomDetailsResponse.room:type_name -> service.room.v1.Room
	4,  // 17: service.room.v1.GetRoomDetailsResponse.members:type_name -> service.room.v1.UserInfo
	17, // 18: service.room.v1.RoomUpdate.member_joined:type_name -> service.room.v1.MemberJoined
	18, // 19: service.room.v1.RoomUpdate.member_left:type_name -> service.room.v1.MemberLeft
	19, // 20: service.room.v1.RoomUpdate.status_changed:type_name -> service.room.v1.RoomStatusChanged
	20, // 21: service.room.v1.RoomUpdate.location_updated:type_name -> service.room.v1.LocationUpdated
	21, // 22: service.room.v1.RoomUpdate.payment_updated:type_name -> service.room.v1.PaymentUpdated
	4,  // 23: service.room.v1.MemberJoined.user:type_name -> service.room.v1.UserInfo
	0,  // 24: service.room.v1.RoomStatusChanged.new_status:type_name -> service.room.v1.RoomStatus
	1,  // 25: service.room.v1.LocationUpdated.new_location:type_name -> service.room.v1.Location
	5,  // 26: service.room.v1.RoomService.CreateRoom:input_type -> service.room.v1.CreateRoomRequest
	7,  // 27: service.room.v1.RoomService.JoinRoom:input_type -> service.room.v1.JoinRoomRequest
	9,  // 28: service.room.v1.RoomService.ExitRoom:input_type -> service.room.v1.ExitRoomRequest
	11, // 29: service.room.v1.RoomService.FindRoom:input_type -> service.room.v1.FindRoomRequest
	13, // 30: service.room.v1.RoomService.GetRoomDetails:input_type -> service.room.v1.GetRoomDetailsRequest
	15, // 31: service.room.v1.RoomService.StreamRoomUpdates:input_type -> service.room.v1.StreamRoomUpdatesRequest
	6,  // 32: service.room.v1.RoomService.CreateRoom:output_type -> service.room.v1.CreateRoomResponse
	8,  // 33: service.room.v1.RoomService.JoinRoom:output_type -> service.room.v1.JoinRoomResponse
	10, // 34: service.room.v1.RoomService.ExitRoom:output_type -> service.room.v1.ExitRoomResponse
	12, // 35: service.room.v1.RoomService.FindRoom:output_type -> service.room.v1.FindRoomResponse
	14, // 36: service.room.v1.RoomService.GetRoomDetails:output_type -> service.room.v1.GetRoomDetailsResponse
	16, // 37: service.room.v1.RoomService.StreamRoomUpdates:output_type -> service.room.v1.RoomUpdate
	32, // [32:38] is the sub-list for method output_type
	26, // [26:32] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	file_room_proto_msgTypes[15].OneofWrappers = []any{
		(*RoomUpdate_MemberJoined)(nil),
		(*RoomUpdate_MemberLeft)(nil),
		(*RoomUpdate_StatusChanged)(nil),
		(*RoomUpdate_LocationUpdated)(nil),
		(*RoomUpdate_PaymentUpdated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
