// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: room.proto

package roomservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomService_CreateRoom_FullMethodName        = "/service.room.v1.RoomService/CreateRoom"
	RoomService_JoinRoom_FullMethodName          = "/service.room.v1.RoomService/JoinRoom"
	RoomService_ExitRoom_FullMethodName          = "/service.room.v1.RoomService/ExitRoom"
	RoomService_FindRoom_FullMethodName          = "/service.room.v1.RoomService/FindRoom"
	RoomService_GetRoomDetails_FullMethodName    = "/service.room.v1.RoomService/GetRoomDetails"
	RoomService_StreamRoomUpdates_FullMethodName = "/service.room.v1.RoomService/StreamRoomUpdates"
)

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomServiceClient interface {
	// CreateRoom создает новую комнату для совместной поездки
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	// JoinRoom позволяет пользователю присоединиться к существующей комнате
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	// ExitRoom позволяет пользователю покинуть комнату
	ExitRoom(ctx context.Context, in *ExitRoomRequest, opts ...grpc.CallOption) (*ExitRoomResponse, error)
	// FindRoom ищет доступные комнаты по заданным критериям
	FindRoom(ctx context.Context, in *FindRoomRequest, opts ...grpc.CallOption) (*FindRoomResponse, error)
	// GetRoomDetails возвращает детальную информацию о конкретной комнате
	GetRoomDetails(ctx context.Context, in *GetRoomDetailsRequest, opts ...grpc.CallOption) (*GetRoomDetailsResponse, error)
	// StreamRoomUpdates предоставляет обновления комнаты в реальном времени
	StreamRoomUpdates(ctx context.Context, in *StreamRoomUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoomUpdate], error)
}

type roomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomServiceClient(cc grpc.ClientConnInterface) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) ExitRoom(ctx context.Context, in *ExitRoomRequest, opts ...grpc.CallOption) (*ExitRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_ExitRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) FindRoom(ctx context.Context, in *FindRoomRequest, opts ...grpc.CallOption) (*FindRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_FindRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetRoomDetails(ctx context.Context, in *GetRoomDetailsRequest, opts ...grpc.CallOption) (*GetRoomDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomDetailsResponse)
	err := c.cc.Invoke(ctx, RoomService_GetRoomDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) StreamRoomUpdates(ctx context.Context, in *StreamRoomUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoomUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoomService_ServiceDesc.Streams[0], RoomService_StreamRoomUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRoomUpdatesRequest, RoomUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoomService_StreamRoomUpdatesClient = grpc.ServerStreamingClient[RoomUpdate]

// RoomServiceServer is the server API for RoomService service.
// All implementations must embed UnimplementedRoomServiceServer
// for forward compatibility.
type RoomServiceServer interface {
	// CreateRoom создает новую комнату для совместной поездки
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	// JoinRoom позволяет пользователю присоединиться к существующей комнате
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	// ExitRoom позволяет пользователю покинуть комнату
	ExitRoom(context.Context, *ExitRoomRequest) (*ExitRoomResponse, error)
	// FindRoom ищет доступные комнаты по заданным критериям
	FindRoom(context.Context, *FindRoomRequest) (*FindRoomResponse, error)
	// GetRoomDetails возвращает детальную информацию о конкретной комнате
	GetRoomDetails(context.Context, *GetRoomDetailsRequest) (*GetRoomDetailsResponse, error)
	// StreamRoomUpdates предоставляет обновления комнаты в реальном времени
	StreamRoomUpdates(*StreamRoomUpdatesRequest, grpc.ServerStreamingServer[RoomUpdate]) error
	mustEmbedUnimplementedRoomServiceServer()
}

// UnimplementedRoomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServiceServer struct{}

func (UnimplementedRoomServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedRoomServiceServer) JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedRoomServiceServer) ExitRoom(context.Context, *ExitRoomRequest) (*ExitRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExitRoom not implemented")
}
func (UnimplementedRoomServiceServer) FindRoom(context.Context, *FindRoomRequest) (*FindRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRoom not implemented")
}
func (UnimplementedRoomServiceServer) GetRoomDetails(context.Context, *GetRoomDetailsRequest) (*GetRoomDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomDetails not implemented")
}
func (UnimplementedRoomServiceServer) StreamRoomUpdates(*StreamRoomUpdatesRequest, grpc.ServerStreamingServer[RoomUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRoomUpdates not implemented")
}
func (UnimplementedRoomServiceServer) mustEmbedUnimplementedRoomServiceServer() {}
func (UnimplementedRoomServiceServer) testEmbeddedByValue()                     {}

// UnsafeRoomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServiceServer will
// result in compilation errors.
type UnsafeRoomServiceServer interface {
	mustEmbedUnimplementedRoomServiceServer()
}

func RegisterRoomServiceServer(s grpc.ServiceRegistrar, srv RoomServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomService_ServiceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_ExitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).ExitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_ExitRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).ExitRoom(ctx, req.(*ExitRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_FindRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).FindRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_FindRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).FindRoom(ctx, req.(*FindRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetRoomDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetRoomDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_GetRoomDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetRoomDetails(ctx, req.(*GetRoomDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_StreamRoomUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRoomUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoomServiceServer).StreamRoomUpdates(m, &grpc.GenericServerStream[StreamRoomUpdatesRequest, RoomUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoomService_StreamRoomUpdatesServer = grpc.ServerStreamingServer[RoomUpdate]

// RoomService_ServiceDesc is the grpc.ServiceDesc for RoomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.room.v1.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _RoomService_JoinRoom_Handler,
		},
		{
			MethodName: "ExitRoom",
			Handler:    _RoomService_ExitRoom_Handler,
		},
		{
			MethodName: "FindRoom",
			Handler:    _RoomService_FindRoom_Handler,
		},
		{
			MethodName: "GetRoomDetails",
			Handler:    _RoomService_GetRoomDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRoomUpdates",
			Handler:       _RoomService_StreamRoomUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "room.proto",
}
